language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer run publish

after_success:
  - bash <(curl -s https://codecov.io/bash)